### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by hyamomar** [alcarbone/S5P_SISR_Toolbox#1]
Thank you for the valuable study in Super-Resolution for the Sentinel-5P, which is highly relevant to my current project. 
I am a postdoctoral researcher at Orleans University, focusing on developing super-resolution techniques for analyzing satellite images to study atmospheric pollution. 
I am interested in **accessing the data** used for your study or any insights you can share regarding its availability.

**Comment by alcarbone** [comment]
Hi, Hyamomar! We appreciate your interest in our study. If you could provide me with your email, I would be pleased to share the employed data with you. You can email me at alcarbone@unisa.it if you'd rather not share it directly here.

**Comment by hyamomar** [comment]
Thank you for your prompt response! 
I appreciate your willingness to share the data. You can reach me at hyam.omar-abbass-ali@univ-orleans.fr
Looking forward to receiving the data and further collaboration.

**Comment by minatoyukinaa** [comment]
I am a postgraduate student studying at Dalian Maritime University, focusing on super-resolution techniques.
I also want to access the data in the paper.Here is my email: namelesscoder@dlmu.edu.cn 
I would be very grateful if I could get your data.
